apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-v4fr
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0065-tenant/tkrw-pr712-0075-0065-app/devfile-sample-v4fr@sha256:2fdf211967d3e8d0df04f5a717b453bd9dae2dcffbfffb1464220bb98b576d9f
        name: my-nodejs
        resources: {}
status: {}
